### PR TITLE
commit pre-push script results

### PR DESCRIPTION
**Pull request by sidoruk-sv**

### CODE REVIEW

**Comment by hugebdu** [comment]
@sidoruk-sv why deps downgrades all over?

**Comment by sidoruk-sv** [comment]
@hugebdu I'm just committing the result of post-push hook for this repo (https://github.com/wix/lerna-script/blob/master/package.json#L28)

I think it is the result of one of `syncModules` (https://github.com/wix/lerna-script/tree/master/tasks/modules) or `dependencies.sync` (https://github.com/wix/lerna-script/tree/master/tasks/dependencies#syncpackageslog-promise)
that are defined in root [`lerna.js`](https://github.com/wix/lerna-script/blob/master/lerna.js#L36)

**Comment by hugebdu** [comment]
indeed. [managed deps](https://github.com/wix/lerna-script/blob/master/lerna.json#L8) those are.
have to be updated.

**Comment by sidoruk-sv** [comment]
@hugebdu updated, also got errors when tried to run `lerna-script depcheck` so removed unused `lerna` from packages.

**Pull request merged**
