### PR TITLE
migrate to lerna-3

### PR DESCRIPTION
**Pull request by viliusl**

### CODE REVIEW

**Comment by zivl** [comment]
why this PR hasn't merged yet?

**Comment by viliusl** [comment]
@zivl mostly due to lack of time and the fact that api needs to be rethought. Previously lerna was a peer dependency - now I have to bundle modules of lerna for things would work. also there are some missing features in new package(s).

So once I will find some more time I will move to 3.x.x

**Comment by hugebdu** [comment]
@viliusl surprisingly I got almost to the same point.
indeed, peerDep with all those smaller lerna pieces plus getting constantly `MaxListenersExceededWarning` from within `@lerna/child-process`

**Comment by viliusl** [comment]
@hugebdu - I merged with master, updated lerna version - except for execs all looks pretty much ok.

for execs we might need to replace with non-lerna version. I mean lerna utils are intended to be executed as one-offs whereas lerna-script does run them multiple times per bin execution so that I guess is an issue:/

**Comment by hugebdu** [comment]
> except for execs

what is about it? the max listeners issue?

**Comment by viliusl** [comment]
@hugebdu yes

**Comment by hugebdu** [comment]
I suspect that's due to the fact there's no `unpipe` call once process exists [here](https://github.com/lerna/lerna/blob/1bb152105f793e33eee37067ee7834c4e6adff1e/core/child-process/index.js#L50-L56)

we may try submitting a PR

**Comment by viliusl** [comment]
@hugebdu - you just might be right - for time-being - https://github.com/wix/lerna-script/pull/112/commits/8320815f468e9a36ae88b2057e7e5a98761e65f0 :)

**Pull request merged**
