### PR TITLE
limit the number of concurrent npm processes and increase prompt page size

### PR DESCRIPTION
**Pull request by eyalpost**

### CODE REVIEW

**Comment by hugebdu** [comment]
@eyalpost why needed? why 8?

**Comment by eyalpost** [comment]
when running lerna `dependencies:latest` script, my mac hangs due to the large number of processes that are created by this script (basically it runs `npm info` for each module).
This bounds the number of processes created (8 seems the best without significantly affecting performance)

**Comment by hugebdu** [comment]
and what's the current limit? is it some math of [# of processes](https://nodejs.org/api/os.html#os_os_cpus)?

maybe let's make it configurable, WDYT?

**Comment by eyalpost** [comment]
currently there is no limit. if there are 200 modules to check then 200 processes will be created.
Why make it configurable? Who will configure it?

**Comment by hugebdu** [comment]
> Why make it configurable? Who will configure it?
ok, but let's make it number of cores available. IMHO more reasonable then just 8

**Pull request merged**
